/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlActor;
import Control.ControlCliente;
import Control.ControlPelicula;
import Modelo.Actor;
import Modelo.Cliente;
import Modelo.Pelicula;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mateo
 */
public class Administrador extends javax.swing.JFrame {

    Principal GUIprincipal;

    DefaultTableModel tablaCuentas;
    DefaultTableModel tablaActores;
    DefaultTableModel tablaPeliculasCuenta;
    DefaultTableModel tablaPeliculasActores;
    DefaultTableModel tablaPeliculasTerror;
    DefaultTableModel tablaRentaTiempo;

    LinkedList<Cliente> datosClientePelicula;
    LinkedList<Pelicula> peliculasRentaCliente;
    LinkedList<Actor> datosActoresPelicula;
    LinkedList<Pelicula> peliculasParticipacionActor;
    LinkedList<String> peliculasCategoriaTerror;
    LinkedList<String> RentasPeriodoTiempo;

    String FechaInicial;
    String FechaFinal;

    String horI;
    String minI;
    String segI;

    String horF;
    String minF;
    String segF;

    String TiempoInicial;
    String TiempoFinal;

    boolean Entrar;

    public Administrador() {
        initComponents();
        this.setLocationRelativeTo(this);

        FechaInicial = null;
        FechaFinal = null;

        datosClientePelicula = new LinkedList<>();
        peliculasRentaCliente = new LinkedList<>();
        datosActoresPelicula = new LinkedList<>();
        peliculasParticipacionActor = new LinkedList<>();
        peliculasCategoriaTerror = new LinkedList<>();
        RentasPeriodoTiempo = new LinkedList<>();
        TraerClientesRegistrados();
        TraerActores();

        Entrar = true;
        TiempoInicial = null;
        TiempoFinal = null;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCuentas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePeliculasC = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        idCliente = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelNombreCliente = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableActores = new javax.swing.JTable();
        jSeparator8 = new javax.swing.JSeparator();
        CodigoActor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelNombreActor = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTablePeliculasA = new javax.swing.JTable();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTablePeliculasTerror = new javax.swing.JTable();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableRenta = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jDateChooserFechaI = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jDateChooserFechaF = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        HoraI = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        MinI = new javax.swing.JTextField();
        SegI = new javax.swing.JTextField();
        HoraF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        MinF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        SegF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ADMINISTRADOR BASE DE DATOS SAKILA");

        jTableCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID cliente", "Nombre Cliente"
            }
        ));
        jScrollPane2.setViewportView(jTableCuentas);
        if (jTableCuentas.getColumnModel().getColumnCount() > 0) {
            jTableCuentas.getColumnModel().getColumn(1).setHeaderValue("Nombre actor");
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Datos clientes");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Datos películas rentados por un cliente");

        jTablePeliculasC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre película", "Año lanzamiento", "Clasificación", "Tarifa renta", "Fecha renta"
            }
        ));
        jScrollPane3.setViewportView(jTablePeliculasC);

        jLabel4.setText("Ingresar el ID del cliente registrado");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelNombreCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNombreCliente.setText("Nombre cliente:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Datos películas donde ha actuado un actor");

        jLabel6.setText("Ingresar el ID del actor");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Datos actores");

        jTableActores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID actor", "Nombre actor"
            }
        ));
        jScrollPane4.setViewportView(jTableActores);
        if (jTableActores.getColumnModel().getColumnCount() > 0) {
            jTableActores.getColumnModel().getColumn(1).setHeaderValue("Nombre actor");
        }

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelNombreActor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNombreActor.setText("Nombre actor:");

        jTablePeliculasA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre película", "Año lanzamiento"
            }
        ));
        jScrollPane5.setViewportView(jTablePeliculasA);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Datos películas categoría terror");

        jTablePeliculasTerror.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre película", "Clasificación"
            }
        ));
        jScrollPane6.setViewportView(jTablePeliculasTerror);

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton3.setText("Desplegar datos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Datos rentas en un período de tiempo: Formato --> YY/MM/DD 00:00:00");

        jTableRenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha renta", "Nombre cliente", "Nombre película"
            }
        ));
        jScrollPane7.setViewportView(jTableRenta);

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel10.setText("Fecha Inicial");

        jLabel11.setText("Fecha Final");

        jLabel12.setText("Hora Inicial");

        HoraI.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText(":");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText(":");

        MinI.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        SegI.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        HoraF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel15.setText("Hora Final");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText(":");

        MinF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText(":");

        SegF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CodigoActor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelNombreActor)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane5)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(219, 483, Short.MAX_VALUE))
                                    .addComponent(jScrollPane3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabelNombreCliente)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jSeparator9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel10)
                                            .addComponent(jDateChooserFechaI, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(HoraI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MinI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SegI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(HoraF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MinF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SegF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel15)
                                            .addComponent(jDateChooserFechaF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane7)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombreCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2)))
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(CodigoActor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)
                                    .addComponent(jLabelNombreActor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(HoraI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(MinI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(SegI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(HoraF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(MinF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(SegF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator12))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //Método que permitirá limpiar el linkedList cada vez que se busque nuevos clientes
        if (peliculasRentaCliente.isEmpty() == false) {

            peliculasRentaCliente.clear();

        }//Fin if

        //*****************************************************************************************
        String codigoCliente = idCliente.getText();

        jLabelNombreCliente.setText("Nombre cliente:  " + EncontrarNombreCliente(codigoCliente));

        ControlPelicula cPelicula = new ControlPelicula();

        peliculasRentaCliente = cPelicula.ConsultaPeliculasCliente(codigoCliente);

        if (peliculasRentaCliente.isEmpty() == false) {

            String data[][] = {};
            String Cabeza[] = {"Nombre película", "Año lanzamiento", "Clasificación", "Tarifa renta", "Fecha renta"};

            tablaPeliculasCuenta = new DefaultTableModel(data, Cabeza);

            jTablePeliculasC.setModel(tablaPeliculasCuenta);

            for (int i = 0; i < peliculasRentaCliente.size(); i++) {

                String nombreP = peliculasRentaCliente.get(i).getNombrePelicula();
                String añoR = peliculasRentaCliente.get(i).getAñoCreacion();
                String clasificacion = peliculasRentaCliente.get(i).getClasificacion();
                String tarifaR = peliculasRentaCliente.get(i).getPrecioRenta();
                String FechaR = peliculasRentaCliente.get(i).getFechaRenta();

                String datos[] = {nombreP, añoR, clasificacion, tarifaR, FechaR};

                tablaPeliculasCuenta.addRow(datos);

            }//Fin for

        } else {

            JOptionPane.showMessageDialog(null, "El ID del cliente ingresado no está registrado.", "Advertencia", JOptionPane.ERROR_MESSAGE);

        }//Fin if

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (peliculasParticipacionActor.isEmpty() == false) {

            peliculasParticipacionActor.clear();

        }//Fin if

        //*****************************************************************************************
        String codigoA = CodigoActor.getText();

        jLabelNombreActor.setText("Nombre actor:  " + EncontrarNombreActor(codigoA));

        ControlPelicula cPelicula = new ControlPelicula();

        peliculasParticipacionActor = cPelicula.ConsultaPeliculasActor(codigoA);

        String data[][] = {};
        String Cabeza[] = {"Nombre película", "Año lanzamiento"};

        tablaPeliculasActores = new DefaultTableModel(data, Cabeza);

        jTablePeliculasA.setModel(tablaPeliculasActores);

        for (int i = 0; i < peliculasParticipacionActor.size(); i++) {

            String NombrePelicula = peliculasParticipacionActor.get(i).getNombrePelicula();
            String AñoLanzamiento = peliculasParticipacionActor.get(i).getAñoCreacion();

            String datos[] = {NombrePelicula, AñoLanzamiento};

            tablaPeliculasActores.addRow(datos);

        }//Fin for

        System.out.println(peliculasParticipacionActor.size());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        ControlPelicula cPelicula = new ControlPelicula();

        peliculasCategoriaTerror = cPelicula.ConsultaPeliculasTerror();

        String data[][] = {};
        String Cabeza[] = {"Nombre película", "Clasificación"};

        tablaPeliculasTerror = new DefaultTableModel(data, Cabeza);

        jTablePeliculasTerror.setModel(tablaPeliculasTerror);

        for (int i = 0; i < peliculasCategoriaTerror.size(); i++) {

            String datosSplint[] = peliculasCategoriaTerror.get(i).split(";");

            String NombrePelicula = datosSplint[0];
            String clasificacion = datosSplint[1];

            String datos[] = {NombrePelicula, clasificacion};

            tablaPeliculasTerror.addRow(datos);

        }//Fin for

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Date date1 = jDateChooserFechaI.getDate();
        Date date2 = jDateChooserFechaF.getDate();

        horF = HoraF.getText();
        minF = MinF.getText();
        segF = SegF.getText();

        horI = HoraI.getText();
        minI = MinI.getText();
        segI = SegI.getText();

        if (date1 != null && date2 != null) {

            Entrar = true;

        } else {

            JOptionPane.showMessageDialog(null, "Por favor, seleccionar una fecha inicial y final.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            Entrar = false;

        }//Fin if

        //Válidar Campos Horas
        ValidarHoraInicial();
        ValirdarHoraFinal();

        //*************************************************************************************************************************************
        if (Entrar) {

            if(RentasPeriodoTiempo.isEmpty() == false){
                
                RentasPeriodoTiempo.clear();
                
            }//Fin if
            
            long Tiempo = date1.getTime();
            long Tiempo2 = date2.getTime();

            java.sql.Date fecha = new java.sql.Date(Tiempo);
            java.sql.Date fecha2 = new java.sql.Date(Tiempo2);

            if (TiempoInicial.equals("00:00:00") || TiempoFinal.equals("00:00:00")) {

                FechaInicial = fecha.toString().substring(2, 10);
                FechaFinal = fecha2.toString().substring(2, 10);
               
            } else {

                FechaInicial = fecha.toString().substring(2, 10) + " " + TiempoInicial;
                FechaFinal = fecha2.toString().substring(2, 10) + " " + TiempoFinal;

            }//Fin if

            ControlCliente Ccliente = new ControlCliente();

            RentasPeriodoTiempo = Ccliente.ConsultaRentasPeriodo(FechaInicial, FechaFinal);

            //*******************************************************************************
            String data[][] = {};
            String Cabeza[] = {"Fecha renta", "Nombre cliente", "Nombre película"};

            tablaRentaTiempo = new DefaultTableModel(data, Cabeza);

            jTableRenta.setModel(tablaRentaTiempo);

            for (int i = 0; i < RentasPeriodoTiempo.size(); i++) {

                String datosSplit[] = RentasPeriodoTiempo.get(i).split(";");

                String FechaRenta = datosSplit[0];
                String NombreCliente = datosSplit[1];
                String NombrePelicula = datosSplit[2];

                String datos[] = {FechaRenta, NombreCliente, NombrePelicula};

                tablaRentaTiempo.addRow(datos);

            }//Fin for  

        }//Fin condición

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        GUIprincipal = new Principal();
        GUIprincipal.show();
        this.dispose();

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    public void TraerClientesRegistrados() {

        ControlCliente cCliente = new ControlCliente();

        datosClientePelicula = cCliente.ConsultarClientesDatos();

        String data[][] = {};
        String Cabeza[] = {"ID cliente", "Nombre cliente"};

        tablaCuentas = new DefaultTableModel(data, Cabeza);

        jTableCuentas.setModel(tablaCuentas);

        for (int i = 0; i < datosClientePelicula.size(); i++) {

            String NombreCliente = datosClientePelicula.get(i).getNombreCliente();
            String PkCliente = datosClientePelicula.get(i).getPkCliente();

            String datos[] = {PkCliente, NombreCliente};

            tablaCuentas.addRow(datos);

        }//Fin for

    }//Fin método

    public String EncontrarNombreCliente(String Pkcliente) {

        String NombreCliente = "";

        for (int i = 0; i < datosClientePelicula.size(); i++) {

            if (datosClientePelicula.get(i).getPkCliente().equals(Pkcliente)) {

                NombreCliente = datosClientePelicula.get(i).getNombreCliente();

            }//Fin if

        }//Fin for

        return NombreCliente;

    }//Fin método

    public void TraerActores() {

        ControlActor cActor = new ControlActor();

        datosActoresPelicula = cActor.ConsultaDatosActor();

        String data[][] = {};
        String Cabeza[] = {"ID actor", "Nombre actor"};

        tablaActores = new DefaultTableModel(data, Cabeza);

        jTableActores.setModel(tablaActores);

        for (int i = 0; i < datosActoresPelicula.size(); i++) {

            String codigoActor = datosActoresPelicula.get(i).getPkActor();
            String NombreActor = datosActoresPelicula.get(i).getNombreActor();

            String datos[] = {codigoActor, NombreActor};

            tablaActores.addRow(datos);

        }//Fin for

    }//Fin método

    public String EncontrarNombreActor(String Pkactor) {

        String NombreActor = "";

        for (int i = 0; i < datosActoresPelicula.size(); i++) {

            if (datosActoresPelicula.get(i).getPkActor().equals(Pkactor)) {

                NombreActor = datosActoresPelicula.get(i).getNombreActor();

            }//Fin if

        }//Fin for

        return NombreActor;

    }//Fin método

    public void ValidarHoraInicial() {

        if (segI.equals("") && minI.equals("") && horI.equals("")) {

            TiempoInicial = "00:00:00";

        } else {

            if (segI.equals("")) {

                segI = "00";

            }//Fin if

            if (minI.equals("")) {

                minI = "00";

            }//Fin if

            if (horI.equals("")) {

                horI = "00";

            }//Fin if

            ValidarDuracionHoraInicial();

        }//Fin if principal

    }//Fin método

    public void ValirdarHoraFinal() {

        if (segF.equals("") && minF.equals("") && horF.equals("")) {

            TiempoFinal = "00:00:00";

        } else {

            if (segF.equals("")) {

                segF = "00";

            }//Fin if

            if (minF.equals("")) {

                minF = "00";

            }//Fin if

            if (horF.equals("")) {

                horF = "00";

            }//Fin if

            ValidarDuracionHoraFinal();

        }//Fin if principal

    }//Fin método

    public void ValidarDuracionHoraInicial() {

        boolean entrar = true;

        if (Integer.parseInt(segI) >= 60) {

            JOptionPane.showMessageDialog(null, "Campo: segundos " + "\nDuración máxima aceptados es: 59 segundos.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            entrar = false;

        }//Fin if

        if (Integer.parseInt(minI) >= 60) {

            JOptionPane.showMessageDialog(null, "Campo: minutos " + "\nDuración máxima aceptados es: 59 minutos.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            entrar = false;

        }//Fin if

        if (Integer.parseInt(horI) > 25) {

            JOptionPane.showMessageDialog(null, "Campo: Horas " + "\nSolo se acepta hasta 24 horas.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            entrar = false;

        }//Fin if

        if (entrar) {

            //Invoca el método para organizar la duración con el formato 00:00:00
            OrganizarDuracionHoraInicial();
            TiempoInicial = horI + ":" + minI + ":" + segI;

        } else {

            Entrar = false;

        }//Fin if

    }//Fin método

    public void OrganizarDuracionHoraInicial() {

        if (segI.length() == 1) {

            segI = "0" + segI;

        }//Fin if

        if (minI.length() == 1) {

            minI = "0" + minI;

        }//Fin if

        if (horI.length() == 1) {

            horI = "0" + horI;

        }//Fin if

    }//Fin método

    public void ValidarDuracionHoraFinal() {

        boolean entrar = true;

        if (Integer.parseInt(segF) >= 60) {

            JOptionPane.showMessageDialog(null, "Campo: segundos " + "\nDuración máxima aceptados es: 59 segundos.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            entrar = false;

        }//Fin if

        if (Integer.parseInt(minF) >= 60) {

            JOptionPane.showMessageDialog(null, "Campo: minutos " + "\nDuración máxima aceptados es: 59 minutos.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            entrar = false;

        }//Fin if

        if (Integer.parseInt(horF) > 25) {

            JOptionPane.showMessageDialog(null, "Campo: Horas " + "\nSolo se acepta hasta 24 horas.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            entrar = false;

        }//Fin if

        if (entrar) {

            //Invoca el método para organizar la duración con el formato 00:00:00
            OrganizarDuracionHoraFinal();
            TiempoFinal = horF + ":" + minF + ":" + segF;

        } else {

            Entrar = false;

        }//Fin if

    }//Fin método

    public void OrganizarDuracionHoraFinal() {

        if (segF.length() == 1) {

            segF = "0" + segF;

        }//Fin if

        if (minF.length() == 1) {

            minF = "0" + minF;

        }//Fin if

        if (horF.length() == 1) {

            horF = "0" + horF;

        }//Fin if

    }//Fin método

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoActor;
    private javax.swing.JTextField HoraF;
    private javax.swing.JTextField HoraI;
    private javax.swing.JTextField MinF;
    private javax.swing.JTextField MinI;
    private javax.swing.JTextField SegF;
    private javax.swing.JTextField SegI;
    private javax.swing.JTextField idCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooserFechaF;
    private com.toedter.calendar.JDateChooser jDateChooserFechaI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNombreActor;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTableActores;
    private javax.swing.JTable jTableCuentas;
    private javax.swing.JTable jTablePeliculasA;
    private javax.swing.JTable jTablePeliculasC;
    private javax.swing.JTable jTablePeliculasTerror;
    private javax.swing.JTable jTableRenta;
    // End of variables declaration//GEN-END:variables
}
